export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_EDIT_PRODUCT_CATEGORY = 'GET_EDIT_PRODUCT_CATEGORY';
export const GET_UPDATE_PRODUCT_CATEGORY = 'GET_UPDATE_PRODUCT_CATEGORY';
export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY';
export const GET_ONE_PRODUCT_CATEGORY = 'GET_ONE_PRODUCT_CATEGORY';
export const CREATE_PRODUCT_CATEGORIES = 'CREATE_PRODUCT_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE';
export const PRODUCT_EDITE = 'PRODUCT_EDITE';


export const GET_USERS = 'GET_USERS';
export const EDIT_USER = 'EDIT_USER';
export const REMOVE_USER = 'REMOVE_USER';


export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';